export const CI_WORKFLOW_TEMPLATE = [
  'name: CI/CD Pipeline',
  'on:',
  '  push:',
  '    branches: [main]',
  '  pull_request:',
  '    branches: [main]',
  '  schedule:',
  '    - cron: "0 */6 * * *"',
  'jobs:',
  '  test:',
  '    runs-on: ubuntu-latest',
  '    steps:',
  '      - uses: actions/checkout@v4',
  '      - name: Install Postman CLI',
  '        run: curl -o- "https://dl-cli.pstmn.io/install/unix.sh" | sh',
  '      - name: Login to Postman CLI',
  '        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}',
  '      - name: Decode SSL certificates',
  "        if: ${{ secrets.POSTMAN_SSL_CLIENT_CERT_B64 != '' }}",
  '        env:',
  '          POSTMAN_SSL_CLIENT_CERT_B64: ${{ secrets.POSTMAN_SSL_CLIENT_CERT_B64 }}',
  '          POSTMAN_SSL_CLIENT_KEY_B64: ${{ secrets.POSTMAN_SSL_CLIENT_KEY_B64 }}',
  '          POSTMAN_SSL_EXTRA_CA_CERTS_B64: ${{ secrets.POSTMAN_SSL_EXTRA_CA_CERTS_B64 }}',
  '        run: |',
  '          mkdir -p "$RUNNER_TEMP/postman-ssl"',
  '          printf %s "$POSTMAN_SSL_CLIENT_CERT_B64" | base64 -d > "$RUNNER_TEMP/postman-ssl/client.crt"',
  '          printf %s "$POSTMAN_SSL_CLIENT_KEY_B64" | base64 -d > "$RUNNER_TEMP/postman-ssl/client.key"',
  '          if [ -n "$POSTMAN_SSL_EXTRA_CA_CERTS_B64" ]; then',
  '            printf %s "$POSTMAN_SSL_EXTRA_CA_CERTS_B64" | base64 -d > "$RUNNER_TEMP/postman-ssl/ca.crt"',
  '          fi',
  '      - name: Run Smoke Tests',
  '        env:',
  '          POSTMAN_SSL_CLIENT_PASSPHRASE: ${{ secrets.POSTMAN_SSL_CLIENT_PASSPHRASE }}',
  '        run: |',
  '          CMD=(postman collection run ${{ vars.POSTMAN_SMOKE_COLLECTION_UID }}',
  '            -e ${{ vars.POSTMAN_ENVIRONMENT_UID }}',
  '            --env-var "baseUrl=${{ vars.RUNTIME_BASE_URL || vars.DEV_GW_URL }}"',
  '            --report-events',
  "            --env-var \"${{ vars.CI_ENVIRONMENT || 'Production' }}\")",
  "          if [ -f \"$RUNNER_TEMP/postman-ssl/client.crt\" ]; then",
  '            CMD+=(--ssl-client-cert "$RUNNER_TEMP/postman-ssl/client.crt"',
  '              --ssl-client-key "$RUNNER_TEMP/postman-ssl/client.key")',
  '            if [ -n "$POSTMAN_SSL_CLIENT_PASSPHRASE" ]; then',
  '              CMD+=(--ssl-client-passphrase "$POSTMAN_SSL_CLIENT_PASSPHRASE")',
  '            fi',
  '            if [ -f "$RUNNER_TEMP/postman-ssl/ca.crt" ]; then',
  '              CMD+=(--ssl-extra-ca-certs "$RUNNER_TEMP/postman-ssl/ca.crt")',
  '            fi',
  '          fi',
  '          "${CMD[@]}"',
  '      - name: Run Contract Tests',
  '        env:',
  '          POSTMAN_SSL_CLIENT_PASSPHRASE: ${{ secrets.POSTMAN_SSL_CLIENT_PASSPHRASE }}',
  '        run: |',
  '          CMD=(postman collection run ${{ vars.POSTMAN_CONTRACT_COLLECTION_UID }}',
  '            -e ${{ vars.POSTMAN_ENVIRONMENT_UID }}',
  '            --env-var "baseUrl=${{ vars.RUNTIME_BASE_URL || vars.DEV_GW_URL }}"',
  '            --report-events',
  "            --env-var \"${{ vars.CI_ENVIRONMENT || 'Production' }}\")",
  "          if [ -f \"$RUNNER_TEMP/postman-ssl/client.crt\" ]; then",
  '            CMD+=(--ssl-client-cert "$RUNNER_TEMP/postman-ssl/client.crt"',
  '              --ssl-client-key "$RUNNER_TEMP/postman-ssl/client.key")',
  '            if [ -n "$POSTMAN_SSL_CLIENT_PASSPHRASE" ]; then',
  '              CMD+=(--ssl-client-passphrase "$POSTMAN_SSL_CLIENT_PASSPHRASE")',
  '            fi',
  '            if [ -f "$RUNNER_TEMP/postman-ssl/ca.crt" ]; then',
  '              CMD+=(--ssl-extra-ca-certs "$RUNNER_TEMP/postman-ssl/ca.crt")',
  '            fi',
  '          fi',
  '          "${CMD[@]}"',
  ''
].join('\\n');
